keys:
  - &primary age1vpmza6twjxadxdghtuxgh9u3d9662s5qsfmf6fm6yljhwypusuuq9keuyz
  - &server age1kl3vfjykcs8tqkfknj0lc4vr04fxpdrg4t3yslc979y0rksd6g7qsaqtdd
creation_rules:
  - path_regex: modules/k3s/secrets\.yaml
    key_groups:
      - age:
          - *primary
          - *server
