apiVersion: ENC[AES256_GCM,data:9B4=,iv:zq1mlYZHGrr4JNjSywLUR3/E3R06+3/BivrIp2w3UXE=,tag:9FvHTzNUVhP2rw4BuV5hIA==,type:str]
kind: ENC[AES256_GCM,data:IwnCo7WF,iv:BD6hKDmZuiR09lFNFA+xKZsm4/NCwP/7TXRItVdXLuA=,tag:qZBya9FItlXmKv5wvlbo/Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FJ0J9bhprSbX2XX68ipR1Ak=,iv:lif9h+NLMzzNaigCECvDLtNl2BIdt1nXRk1+Ls35bpQ=,tag:GdRu6YyxtKxDA+59jRj6wQ==,type:str]
    namespace: ENC[AES256_GCM,data:r/x8hM4AzdldZQ==,iv:RyisEvIKpB/GCZeLDcKoM2c8tHyNDeeeYmDm3SLPv08=,tag:NtiSTOj+OVIjvfJfSL79mg==,type:str]
type: ENC[AES256_GCM,data:CkjV+9JP,iv:9lj8VLo3Xsc01PpCkvmmGxfs6VoyAaG7JOZGY3PrQXI=,tag:SumqTOGO9Ql0plTuJBmFXg==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Y9K3ymmkFrhovMljkK1JYCv5cVciMw==,iv:NViTUDh6yb/rTqIVnl1eOb52l/BmCbCgM4H4ikEWo4E=,tag:FS4GhzDPcN62NxX5beuq+g==,type:str]
sops:
    age:
        - recipient: age1vpmza6twjxadxdghtuxgh9u3d9662s5qsfmf6fm6yljhwypusuuq9keuyz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcDFGZkh3Q2xkejQxYkdD
            T3p3Qk8zSlZRdUhweTRCQWdyNno1eUFhUDFjClYrZS9kNjd0Wkp0OXhSNktxR1g4
            NjA4a2VTRjR6VUVIeW9oVWZJa1dXb3cKLS0tICtzd0NnaFV0U1dmcnhjY1FaNE4r
            R2lBL2lsZ3cwTFZUaTJkNmxJTjlBOWMKk3QP5HsOnK4haYYO64hTDsvnoh+cWDwb
            BmqIdyQBQPXAqDFydhV558i64+tjFIu91a9aSOOQJAffYag30IOZMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T03:13:12Z"
    mac: ENC[AES256_GCM,data:jADYYaPTTSscw1Jl1Nr8tFerEFifvSSUb/EmoxihuzqG7uqHb/sPcOIbZ58u8oSwacL3mPpd8bJp8tYg7DqGhxdrOQ6MgNxh8IjI/urOG8ZSAqcGIMNtSmu7tMsUViAp76RVkaDPNyoShzDnuiUjpKEejcc66hit5KREQUihUsQ=,iv:yGGHXJKT4D2cubvjkVPX343caUgdmwHM0urA7KSJf8Q=,tag:TkdFgM0cGaiGpSu0RFaxwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
